name: '532_HomeScope'
channels:
    - conda-forge
    - defaults
dependencies:
    - ipykernel
    - altair=5.3.*  
    - dash=2.16.*
    - dash-bootstrap-components=1.5.*
    - plotly=5.19.*
    - pip
    - pandas=2.2.* 
    - pyarrow=15.0.*
    - pip:
        - dash-daq==0.5.* 
        - dash-vega-components==0.10.*
        - vega-datasets==0.9.*
        - joblib==1.4.*

