name: '532_HomeScope'
channels:
    - conda-forge
    - defaults
dependencies:
    - ipykernel
    - altair  
    - dash=2.16.*
    - dash-bootstrap-components=1.5.*
    - plotly=5.19.*
    - r-base
    - r-tidyverse
    - r-shiny
    - r-languageserver
    - r-plotly
    - pip
    - pandas=2.2.*  
    - pip:
        - dash-daq==0.5.* 

